---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/talife/gitops-local-apps.git

